### ISSUE TITLE
Який принцип роботи додатку?

### ISSUE THREAD

**Issue by BrunIF** [idutka/ocr#1]
Як повинна працювати програма.
Якщо, то ще пре-альфа і вона не працює, тоді зрозуміло.
Але добре було б вже зробити щось робоче.

**Comment by idutka** [comment]
Це ще не робоча версія, найближчим часом дороблю її.

**Comment by BrunIF** [comment]
Напишіть принцип дії роботи. Це можна буде використати у дипломі.

**Comment by idutka** [comment]
програму дописав, уже як є )
принцип роботи розписаний у 3 розділі основної частини
